language: node_js
node_js:
  - "8"

install:
- npm install
script:
- npm run build:dev
- npm run build
- npm run build-zip

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master
    tags: true
